version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db
    networks:
      - backend

  web:
    image: nginx:1.25-alpine
    container_name: nginx-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    networks:
      - backend
    command: --default-time-zone='+09:00'

volumes:
  db-data: 

networks:
  backend:
    driver: bridge
